<template>
  <div class="icondiv"><div><icon name='g-3d-rotation' scale='2'></icon><br>g-3d-rotation</div>
<div><icon name='g-ac-unit' scale='2'></icon><br>g-ac-unit</div>
<div><icon name='g-access-alarm' scale='2'></icon><br>g-access-alarm</div>
<div><icon name='g-access-alarms' scale='2'></icon><br>g-access-alarms</div>
<div><icon name='g-access-time' scale='2'></icon><br>g-access-time</div>
<div><icon name='g-accessibility' scale='2'></icon><br>g-accessibility</div>
<div><icon name='g-accessible' scale='2'></icon><br>g-accessible</div>
<div><icon name='g-account-balance' scale='2'></icon><br>g-account-balance</div>
<div><icon name='g-account-balance-wallet' scale='2'></icon><br>g-account-balance-wallet</div>
<div><icon name='g-account-box' scale='2'></icon><br>g-account-box</div>
<div><icon name='g-account-child' scale='2'></icon><br>g-account-child</div>
<div><icon name='g-account-circle' scale='2'></icon><br>g-account-circle</div>
<div><icon name='g-adb' scale='2'></icon><br>g-adb</div>
<div><icon name='g-add' scale='2'></icon><br>g-add</div>
<div><icon name='g-add-a-photo' scale='2'></icon><br>g-add-a-photo</div>
<div><icon name='g-add-alarm' scale='2'></icon><br>g-add-alarm</div>
<div><icon name='g-add-alert' scale='2'></icon><br>g-add-alert</div>
<div><icon name='g-add-box' scale='2'></icon><br>g-add-box</div>
<div><icon name='g-add-circle' scale='2'></icon><br>g-add-circle</div>
<div><icon name='g-add-circle-outline' scale='2'></icon><br>g-add-circle-outline</div>
<div><icon name='g-add-location' scale='2'></icon><br>g-add-location</div>
<div><icon name='g-add-shopping-cart' scale='2'></icon><br>g-add-shopping-cart</div>
<div><icon name='g-add-to-photos' scale='2'></icon><br>g-add-to-photos</div>
<div><icon name='g-add-to-queue' scale='2'></icon><br>g-add-to-queue</div>
<div><icon name='g-adjust' scale='2'></icon><br>g-adjust</div>
<div><icon name='g-airline-seat-flat' scale='2'></icon><br>g-airline-seat-flat</div>
<div><icon name='g-airline-seat-flat-angled' scale='2'></icon><br>g-airline-seat-flat-angled</div>
<div><icon name='g-airline-seat-individual-suite' scale='2'></icon><br>g-airline-seat-individual-suite</div>
<div><icon name='g-airline-seat-legroom-extra' scale='2'></icon><br>g-airline-seat-legroom-extra</div>
<div><icon name='g-airline-seat-legroom-normal' scale='2'></icon><br>g-airline-seat-legroom-normal</div>
<div><icon name='g-airline-seat-legroom-reduced' scale='2'></icon><br>g-airline-seat-legroom-reduced</div>
<div><icon name='g-airline-seat-recline-extra' scale='2'></icon><br>g-airline-seat-recline-extra</div>
<div><icon name='g-airline-seat-recline-normal' scale='2'></icon><br>g-airline-seat-recline-normal</div>
<div><icon name='g-airplanemode-active' scale='2'></icon><br>g-airplanemode-active</div>
<div><icon name='g-airplanemode-inactive' scale='2'></icon><br>g-airplanemode-inactive</div>
<div><icon name='g-airplanemode-off' scale='2'></icon><br>g-airplanemode-off</div>
<div><icon name='g-airplanemode-on' scale='2'></icon><br>g-airplanemode-on</div>
<div><icon name='g-airplay' scale='2'></icon><br>g-airplay</div>
<div><icon name='g-airport-shuttle' scale='2'></icon><br>g-airport-shuttle</div>
<div><icon name='g-alarm' scale='2'></icon><br>g-alarm</div>
<div><icon name='g-alarm-add' scale='2'></icon><br>g-alarm-add</div>
<div><icon name='g-alarm-off' scale='2'></icon><br>g-alarm-off</div>
<div><icon name='g-alarm-on' scale='2'></icon><br>g-alarm-on</div>
<div><icon name='g-album' scale='2'></icon><br>g-album</div>
<div><icon name='g-all-inclusive' scale='2'></icon><br>g-all-inclusive</div>
<div><icon name='g-android' scale='2'></icon><br>g-android</div>
<div><icon name='g-announcement' scale='2'></icon><br>g-announcement</div>
<div><icon name='g-apps' scale='2'></icon><br>g-apps</div>
<div><icon name='g-archive' scale='2'></icon><br>g-archive</div>
<div><icon name='g-arrow-back' scale='2'></icon><br>g-arrow-back</div>
<div><icon name='g-arrow-drop-down' scale='2'></icon><br>g-arrow-drop-down</div>
<div><icon name='g-arrow-drop-down-circle' scale='2'></icon><br>g-arrow-drop-down-circle</div>
<div><icon name='g-arrow-drop-up' scale='2'></icon><br>g-arrow-drop-up</div>
<div><icon name='g-arrow-forward' scale='2'></icon><br>g-arrow-forward</div>
<div><icon name='g-arrow-upward' scale='2'></icon><br>g-arrow-upward</div>
<div><icon name='g-aspect-ratio' scale='2'></icon><br>g-aspect-ratio</div>
<div><icon name='g-assessment' scale='2'></icon><br>g-assessment</div>
<div><icon name='g-assignment' scale='2'></icon><br>g-assignment</div>
<div><icon name='g-assignment-ind' scale='2'></icon><br>g-assignment-ind</div>
<div><icon name='g-assignment-late' scale='2'></icon><br>g-assignment-late</div>
<div><icon name='g-assignment-return' scale='2'></icon><br>g-assignment-return</div>
<div><icon name='g-assignment-returned' scale='2'></icon><br>g-assignment-returned</div>
<div><icon name='g-assignment-turned-in' scale='2'></icon><br>g-assignment-turned-in</div>
<div><icon name='g-assistant' scale='2'></icon><br>g-assistant</div>
<div><icon name='g-assistant-photo' scale='2'></icon><br>g-assistant-photo</div>
<div><icon name='g-attach-file' scale='2'></icon><br>g-attach-file</div>
<div><icon name='g-attach-money' scale='2'></icon><br>g-attach-money</div>
<div><icon name='g-attachment' scale='2'></icon><br>g-attachment</div>
<div><icon name='g-audiotrack' scale='2'></icon><br>g-audiotrack</div>
<div><icon name='g-autorenew' scale='2'></icon><br>g-autorenew</div>
<div><icon name='g-av-timer' scale='2'></icon><br>g-av-timer</div>
<div><icon name='g-backspace' scale='2'></icon><br>g-backspace</div>
<div><icon name='g-backup' scale='2'></icon><br>g-backup</div>
<div><icon name='g-battery-20' scale='2'></icon><br>g-battery-20</div>
<div><icon name='g-battery-30' scale='2'></icon><br>g-battery-30</div>
<div><icon name='g-battery-50' scale='2'></icon><br>g-battery-50</div>
<div><icon name='g-battery-60' scale='2'></icon><br>g-battery-60</div>
<div><icon name='g-battery-80' scale='2'></icon><br>g-battery-80</div>
<div><icon name='g-battery-90' scale='2'></icon><br>g-battery-90</div>
<div><icon name='g-battery-alert' scale='2'></icon><br>g-battery-alert</div>
<div><icon name='g-battery-charging-20' scale='2'></icon><br>g-battery-charging-20</div>
<div><icon name='g-battery-charging-30' scale='2'></icon><br>g-battery-charging-30</div>
<div><icon name='g-battery-charging-50' scale='2'></icon><br>g-battery-charging-50</div>
<div><icon name='g-battery-charging-60' scale='2'></icon><br>g-battery-charging-60</div>
<div><icon name='g-battery-charging-80' scale='2'></icon><br>g-battery-charging-80</div>
<div><icon name='g-battery-charging-90' scale='2'></icon><br>g-battery-charging-90</div>
<div><icon name='g-battery-charging-full' scale='2'></icon><br>g-battery-charging-full</div>
<div><icon name='g-battery-full' scale='2'></icon><br>g-battery-full</div>
<div><icon name='g-battery-std' scale='2'></icon><br>g-battery-std</div>
<div><icon name='g-battery-unknown' scale='2'></icon><br>g-battery-unknown</div>
<div><icon name='g-beach-access' scale='2'></icon><br>g-beach-access</div>
<div><icon name='g-beenhere' scale='2'></icon><br>g-beenhere</div>
<div><icon name='g-block' scale='2'></icon><br>g-block</div>
<div><icon name='g-bluetooth' scale='2'></icon><br>g-bluetooth</div>
<div><icon name='g-bluetooth-audio' scale='2'></icon><br>g-bluetooth-audio</div>
<div><icon name='g-bluetooth-connected' scale='2'></icon><br>g-bluetooth-connected</div>
<div><icon name='g-bluetooth-disabled' scale='2'></icon><br>g-bluetooth-disabled</div>
<div><icon name='g-bluetooth-searching' scale='2'></icon><br>g-bluetooth-searching</div>
<div><icon name='g-blur-circular' scale='2'></icon><br>g-blur-circular</div>
<div><icon name='g-blur-linear' scale='2'></icon><br>g-blur-linear</div>
<div><icon name='g-blur-off' scale='2'></icon><br>g-blur-off</div>
<div><icon name='g-blur-on' scale='2'></icon><br>g-blur-on</div>
<div><icon name='g-book' scale='2'></icon><br>g-book</div>
<div><icon name='g-bookmark' scale='2'></icon><br>g-bookmark</div>
<div><icon name='g-bookmark-border' scale='2'></icon><br>g-bookmark-border</div>
<div><icon name='g-bookmark-outline' scale='2'></icon><br>g-bookmark-outline</div>
<div><icon name='g-border-all' scale='2'></icon><br>g-border-all</div>
<div><icon name='g-border-bottom' scale='2'></icon><br>g-border-bottom</div>
<div><icon name='g-border-clear' scale='2'></icon><br>g-border-clear</div>
<div><icon name='g-border-color' scale='2'></icon><br>g-border-color</div>
<div><icon name='g-border-horizontal' scale='2'></icon><br>g-border-horizontal</div>
<div><icon name='g-border-inner' scale='2'></icon><br>g-border-inner</div>
<div><icon name='g-border-left' scale='2'></icon><br>g-border-left</div>
<div><icon name='g-border-outer' scale='2'></icon><br>g-border-outer</div>
<div><icon name='g-border-right' scale='2'></icon><br>g-border-right</div>
<div><icon name='g-border-style' scale='2'></icon><br>g-border-style</div>
<div><icon name='g-border-top' scale='2'></icon><br>g-border-top</div>
<div><icon name='g-border-vertical' scale='2'></icon><br>g-border-vertical</div>
<div><icon name='g-branding-watermark' scale='2'></icon><br>g-branding-watermark</div>
<div><icon name='g-brightness-1' scale='2'></icon><br>g-brightness-1</div>
<div><icon name='g-brightness-2' scale='2'></icon><br>g-brightness-2</div>
<div><icon name='g-brightness-3' scale='2'></icon><br>g-brightness-3</div>
<div><icon name='g-brightness-4' scale='2'></icon><br>g-brightness-4</div>
<div><icon name='g-brightness-5' scale='2'></icon><br>g-brightness-5</div>
<div><icon name='g-brightness-6' scale='2'></icon><br>g-brightness-6</div>
<div><icon name='g-brightness-7' scale='2'></icon><br>g-brightness-7</div>
<div><icon name='g-brightness-auto' scale='2'></icon><br>g-brightness-auto</div>
<div><icon name='g-brightness-high' scale='2'></icon><br>g-brightness-high</div>
<div><icon name='g-brightness-low' scale='2'></icon><br>g-brightness-low</div>
<div><icon name='g-brightness-medium' scale='2'></icon><br>g-brightness-medium</div>
<div><icon name='g-broken-image' scale='2'></icon><br>g-broken-image</div>
<div><icon name='g-brush' scale='2'></icon><br>g-brush</div>
<div><icon name='g-bug-report' scale='2'></icon><br>g-bug-report</div>
<div><icon name='g-build' scale='2'></icon><br>g-build</div>
<div><icon name='g-burst-mode' scale='2'></icon><br>g-burst-mode</div>
<div><icon name='g-business' scale='2'></icon><br>g-business</div>
<div><icon name='g-business-center' scale='2'></icon><br>g-business-center</div>
<div><icon name='g-cached' scale='2'></icon><br>g-cached</div>
<div><icon name='g-cake' scale='2'></icon><br>g-cake</div>
<div><icon name='g-call' scale='2'></icon><br>g-call</div>
<div><icon name='g-call-end' scale='2'></icon><br>g-call-end</div>
<div><icon name='g-call-made' scale='2'></icon><br>g-call-made</div>
<div><icon name='g-call-merge' scale='2'></icon><br>g-call-merge</div>
<div><icon name='g-call-missed' scale='2'></icon><br>g-call-missed</div>
<div><icon name='g-call-received' scale='2'></icon><br>g-call-received</div>
<div><icon name='g-call-split' scale='2'></icon><br>g-call-split</div>
<div><icon name='g-call-to-action' scale='2'></icon><br>g-call-to-action</div>
<div><icon name='g-camera' scale='2'></icon><br>g-camera</div>
<div><icon name='g-camera-alt' scale='2'></icon><br>g-camera-alt</div>
<div><icon name='g-camera-enhance' scale='2'></icon><br>g-camera-enhance</div>
<div><icon name='g-camera-front' scale='2'></icon><br>g-camera-front</div>
<div><icon name='g-camera-rear' scale='2'></icon><br>g-camera-rear</div>
<div><icon name='g-camera-roll' scale='2'></icon><br>g-camera-roll</div>
<div><icon name='g-cancel' scale='2'></icon><br>g-cancel</div>
<div><icon name='g-card-giftcard' scale='2'></icon><br>g-card-giftcard</div>
<div><icon name='g-card-membership' scale='2'></icon><br>g-card-membership</div>
<div><icon name='g-card-travel' scale='2'></icon><br>g-card-travel</div>
<div><icon name='g-casino' scale='2'></icon><br>g-casino</div>
<div><icon name='g-cast' scale='2'></icon><br>g-cast</div>
<div><icon name='g-cast-connected' scale='2'></icon><br>g-cast-connected</div>
<div><icon name='g-center-focus-strong' scale='2'></icon><br>g-center-focus-strong</div>
<div><icon name='g-center-focus-weak' scale='2'></icon><br>g-center-focus-weak</div>
<div><icon name='g-change-history' scale='2'></icon><br>g-change-history</div>
<div><icon name='g-chat' scale='2'></icon><br>g-chat</div>
<div><icon name='g-chat-bubble' scale='2'></icon><br>g-chat-bubble</div>
<div><icon name='g-chat-bubble-outline' scale='2'></icon><br>g-chat-bubble-outline</div>
<div><icon name='g-check' scale='2'></icon><br>g-check</div>
<div><icon name='g-check-box' scale='2'></icon><br>g-check-box</div>
<div><icon name='g-check-box-outline-blank' scale='2'></icon><br>g-check-box-outline-blank</div>
<div><icon name='g-check-circle' scale='2'></icon><br>g-check-circle</div>
<div><icon name='g-chevron-left' scale='2'></icon><br>g-chevron-left</div>
<div><icon name='g-chevron-right' scale='2'></icon><br>g-chevron-right</div>
<div><icon name='g-child-care' scale='2'></icon><br>g-child-care</div>
<div><icon name='g-child-friendly' scale='2'></icon><br>g-child-friendly</div>
<div><icon name='g-chrome-reader-mode' scale='2'></icon><br>g-chrome-reader-mode</div>
<div><icon name='g-class' scale='2'></icon><br>g-class</div>
<div><icon name='g-clear' scale='2'></icon><br>g-clear</div>
<div><icon name='g-clear-all' scale='2'></icon><br>g-clear-all</div>
<div><icon name='g-close' scale='2'></icon><br>g-close</div>
<div><icon name='g-closed-caption' scale='2'></icon><br>g-closed-caption</div>
<div><icon name='g-cloud' scale='2'></icon><br>g-cloud</div>
<div><icon name='g-cloud-circle' scale='2'></icon><br>g-cloud-circle</div>
<div><icon name='g-cloud-done' scale='2'></icon><br>g-cloud-done</div>
<div><icon name='g-cloud-download' scale='2'></icon><br>g-cloud-download</div>
<div><icon name='g-cloud-off' scale='2'></icon><br>g-cloud-off</div>
<div><icon name='g-cloud-queue' scale='2'></icon><br>g-cloud-queue</div>
<div><icon name='g-cloud-upload' scale='2'></icon><br>g-cloud-upload</div>
<div><icon name='g-code' scale='2'></icon><br>g-code</div>
<div><icon name='g-collections' scale='2'></icon><br>g-collections</div>
<div><icon name='g-collections-bookmark' scale='2'></icon><br>g-collections-bookmark</div>
<div><icon name='g-color-lens' scale='2'></icon><br>g-color-lens</div>
<div><icon name='g-colorize' scale='2'></icon><br>g-colorize</div>
<div><icon name='g-comment' scale='2'></icon><br>g-comment</div>
<div><icon name='g-compare' scale='2'></icon><br>g-compare</div>
<div><icon name='g-compare-arrows' scale='2'></icon><br>g-compare-arrows</div>
<div><icon name='g-computer' scale='2'></icon><br>g-computer</div>
<div><icon name='g-confirmation-number' scale='2'></icon><br>g-confirmation-number</div>
<div><icon name='g-contact-mail' scale='2'></icon><br>g-contact-mail</div>
<div><icon name='g-contact-phone' scale='2'></icon><br>g-contact-phone</div>
<div><icon name='g-contacts' scale='2'></icon><br>g-contacts</div>
<div><icon name='g-content-copy' scale='2'></icon><br>g-content-copy</div>
<div><icon name='g-content-cut' scale='2'></icon><br>g-content-cut</div>
<div><icon name='g-content-paste' scale='2'></icon><br>g-content-paste</div>
<div><icon name='g-control-point' scale='2'></icon><br>g-control-point</div>
<div><icon name='g-control-point-duplicate' scale='2'></icon><br>g-control-point-duplicate</div>
<div><icon name='g-create' scale='2'></icon><br>g-create</div>
<div><icon name='g-create-new-folder' scale='2'></icon><br>g-create-new-folder</div>
<div><icon name='g-credit-card' scale='2'></icon><br>g-credit-card</div>
<div><icon name='g-crop-16-9' scale='2'></icon><br>g-crop-16-9</div>
<div><icon name='g-crop' scale='2'></icon><br>g-crop</div>
<div><icon name='g-crop-3-2' scale='2'></icon><br>g-crop-3-2</div>
<div><icon name='g-crop-5-4' scale='2'></icon><br>g-crop-5-4</div>
<div><icon name='g-crop-7-5' scale='2'></icon><br>g-crop-7-5</div>
<div><icon name='g-crop-din' scale='2'></icon><br>g-crop-din</div>
<div><icon name='g-crop-free' scale='2'></icon><br>g-crop-free</div>
<div><icon name='g-crop-landscape' scale='2'></icon><br>g-crop-landscape</div>
<div><icon name='g-crop-original' scale='2'></icon><br>g-crop-original</div>
<div><icon name='g-crop-portrait' scale='2'></icon><br>g-crop-portrait</div>
<div><icon name='g-crop-rotate' scale='2'></icon><br>g-crop-rotate</div>
<div><icon name='g-crop-square' scale='2'></icon><br>g-crop-square</div>
<div><icon name='g-dashboard' scale='2'></icon><br>g-dashboard</div>
<div><icon name='g-data-usage' scale='2'></icon><br>g-data-usage</div>
<div><icon name='g-date-range' scale='2'></icon><br>g-date-range</div>
<div><icon name='g-dehaze' scale='2'></icon><br>g-dehaze</div>
<div><icon name='g-delete' scale='2'></icon><br>g-delete</div>
<div><icon name='g-delete-forever' scale='2'></icon><br>g-delete-forever</div>
<div><icon name='g-delete-sweep' scale='2'></icon><br>g-delete-sweep</div>
<div><icon name='g-description' scale='2'></icon><br>g-description</div>
<div><icon name='g-desktop-mac' scale='2'></icon><br>g-desktop-mac</div>
<div><icon name='g-desktop-windows' scale='2'></icon><br>g-desktop-windows</div>
<div><icon name='g-details' scale='2'></icon><br>g-details</div>
<div><icon name='g-developer-board' scale='2'></icon><br>g-developer-board</div>
<div><icon name='g-developer-mode' scale='2'></icon><br>g-developer-mode</div>
<div><icon name='g-device-hub' scale='2'></icon><br>g-device-hub</div>
<div><icon name='g-devices' scale='2'></icon><br>g-devices</div>
<div><icon name='g-devices-other' scale='2'></icon><br>g-devices-other</div>
<div><icon name='g-dialer-sip' scale='2'></icon><br>g-dialer-sip</div>
<div><icon name='g-dialpad' scale='2'></icon><br>g-dialpad</div>
<div><icon name='g-directions' scale='2'></icon><br>g-directions</div>
<div><icon name='g-directions-bike' scale='2'></icon><br>g-directions-bike</div>
<div><icon name='g-directions-boat' scale='2'></icon><br>g-directions-boat</div>
<div><icon name='g-directions-bus' scale='2'></icon><br>g-directions-bus</div>
<div><icon name='g-directions-car' scale='2'></icon><br>g-directions-car</div>
<div><icon name='g-directions-ferry' scale='2'></icon><br>g-directions-ferry</div>
<div><icon name='g-directions-railway' scale='2'></icon><br>g-directions-railway</div>
<div><icon name='g-directions-run' scale='2'></icon><br>g-directions-run</div>
<div><icon name='g-directions-subway' scale='2'></icon><br>g-directions-subway</div>
<div><icon name='g-directions-train' scale='2'></icon><br>g-directions-train</div>
<div><icon name='g-directions-transit' scale='2'></icon><br>g-directions-transit</div>
<div><icon name='g-directions-walk' scale='2'></icon><br>g-directions-walk</div>
<div><icon name='g-disc-full' scale='2'></icon><br>g-disc-full</div>
<div><icon name='g-dnd-forwardslash' scale='2'></icon><br>g-dnd-forwardslash</div>
<div><icon name='g-dnd-on' scale='2'></icon><br>g-dnd-on</div>
<div><icon name='g-dns' scale='2'></icon><br>g-dns</div>
<div><icon name='g-do-not-disturb' scale='2'></icon><br>g-do-not-disturb</div>
<div><icon name='g-do-not-disturb-alt' scale='2'></icon><br>g-do-not-disturb-alt</div>
<div><icon name='g-do-not-disturb-off' scale='2'></icon><br>g-do-not-disturb-off</div>
<div><icon name='g-do-not-disturb-on' scale='2'></icon><br>g-do-not-disturb-on</div>
<div><icon name='g-dock' scale='2'></icon><br>g-dock</div>
<div><icon name='g-domain' scale='2'></icon><br>g-domain</div>
<div><icon name='g-done' scale='2'></icon><br>g-done</div>
<div><icon name='g-done-all' scale='2'></icon><br>g-done-all</div>
<div><icon name='g-donut-large' scale='2'></icon><br>g-donut-large</div>
<div><icon name='g-donut-small' scale='2'></icon><br>g-donut-small</div>
<div><icon name='g-drafts' scale='2'></icon><br>g-drafts</div>
<div><icon name='g-drag-handle' scale='2'></icon><br>g-drag-handle</div>
<div><icon name='g-drive-eta' scale='2'></icon><br>g-drive-eta</div>
<div><icon name='g-dvr' scale='2'></icon><br>g-dvr</div>
<div><icon name='g-edit' scale='2'></icon><br>g-edit</div>
<div><icon name='g-edit-location' scale='2'></icon><br>g-edit-location</div>
<div><icon name='g-eject' scale='2'></icon><br>g-eject</div>
<div><icon name='g-email' scale='2'></icon><br>g-email</div>
<div><icon name='g-enhanced-encryption' scale='2'></icon><br>g-enhanced-encryption</div>
<div><icon name='g-equalizer' scale='2'></icon><br>g-equalizer</div>
<div><icon name='g-error' scale='2'></icon><br>g-error</div>
<div><icon name='g-error-outline' scale='2'></icon><br>g-error-outline</div>
<div><icon name='g-euro-symbol' scale='2'></icon><br>g-euro-symbol</div>
<div><icon name='g-ev-station' scale='2'></icon><br>g-ev-station</div>
<div><icon name='g-event' scale='2'></icon><br>g-event</div>
<div><icon name='g-event-available' scale='2'></icon><br>g-event-available</div>
<div><icon name='g-event-busy' scale='2'></icon><br>g-event-busy</div>
<div><icon name='g-event-note' scale='2'></icon><br>g-event-note</div>
<div><icon name='g-event-seat' scale='2'></icon><br>g-event-seat</div>
<div><icon name='g-exit-to-app' scale='2'></icon><br>g-exit-to-app</div>
<div><icon name='g-expand-less' scale='2'></icon><br>g-expand-less</div>
<div><icon name='g-expand-more' scale='2'></icon><br>g-expand-more</div>
<div><icon name='g-explicit' scale='2'></icon><br>g-explicit</div>
<div><icon name='g-explore' scale='2'></icon><br>g-explore</div>
<div><icon name='g-exposure' scale='2'></icon><br>g-exposure</div>
<div><icon name='g-exposure-minus-1' scale='2'></icon><br>g-exposure-minus-1</div>
<div><icon name='g-exposure-minus-2' scale='2'></icon><br>g-exposure-minus-2</div>
<div><icon name='g-exposure-neg-1' scale='2'></icon><br>g-exposure-neg-1</div>
<div><icon name='g-exposure-neg-2' scale='2'></icon><br>g-exposure-neg-2</div>
<div><icon name='g-exposure-plus-1' scale='2'></icon><br>g-exposure-plus-1</div>
<div><icon name='g-exposure-plus-2' scale='2'></icon><br>g-exposure-plus-2</div>
<div><icon name='g-exposure-zero' scale='2'></icon><br>g-exposure-zero</div>
<div><icon name='g-extension' scale='2'></icon><br>g-extension</div>
<div><icon name='g-face' scale='2'></icon><br>g-face</div>
<div><icon name='g-face-unlock' scale='2'></icon><br>g-face-unlock</div>
<div><icon name='g-fast-forward' scale='2'></icon><br>g-fast-forward</div>
<div><icon name='g-fast-rewind' scale='2'></icon><br>g-fast-rewind</div>
<div><icon name='g-favorite' scale='2'></icon><br>g-favorite</div>
<div><icon name='g-favorite-border' scale='2'></icon><br>g-favorite-border</div>
<div><icon name='g-favorite-outline' scale='2'></icon><br>g-favorite-outline</div>
<div><icon name='g-featured-play-list' scale='2'></icon><br>g-featured-play-list</div>
<div><icon name='g-featured-video' scale='2'></icon><br>g-featured-video</div>
<div><icon name='g-feedback' scale='2'></icon><br>g-feedback</div>
<div><icon name='g-fiber-dvr' scale='2'></icon><br>g-fiber-dvr</div>
<div><icon name='g-fiber-new' scale='2'></icon><br>g-fiber-new</div>
<div><icon name='g-fiber-pin' scale='2'></icon><br>g-fiber-pin</div>
<div><icon name='g-fiber-smart-record' scale='2'></icon><br>g-fiber-smart-record</div>
<div><icon name='g-file-download' scale='2'></icon><br>g-file-download</div>
<div><icon name='g-file-upload' scale='2'></icon><br>g-file-upload</div>
<div><icon name='g-filter-1' scale='2'></icon><br>g-filter-1</div>
<div><icon name='g-filter' scale='2'></icon><br>g-filter</div>
<div><icon name='g-filter-2' scale='2'></icon><br>g-filter-2</div>
<div><icon name='g-filter-3' scale='2'></icon><br>g-filter-3</div>
<div><icon name='g-filter-4' scale='2'></icon><br>g-filter-4</div>
<div><icon name='g-filter-5' scale='2'></icon><br>g-filter-5</div>
<div><icon name='g-filter-6' scale='2'></icon><br>g-filter-6</div>
<div><icon name='g-filter-7' scale='2'></icon><br>g-filter-7</div>
<div><icon name='g-filter-8' scale='2'></icon><br>g-filter-8</div>
<div><icon name='g-filter-9' scale='2'></icon><br>g-filter-9</div>
<div><icon name='g-filter-9-plus' scale='2'></icon><br>g-filter-9-plus</div>
<div><icon name='g-filter-b-and-w' scale='2'></icon><br>g-filter-b-and-w</div>
<div><icon name='g-filter-center-focus' scale='2'></icon><br>g-filter-center-focus</div>
<div><icon name='g-filter-drama' scale='2'></icon><br>g-filter-drama</div>
<div><icon name='g-filter-frames' scale='2'></icon><br>g-filter-frames</div>
<div><icon name='g-filter-hdr' scale='2'></icon><br>g-filter-hdr</div>
<div><icon name='g-filter-list' scale='2'></icon><br>g-filter-list</div>
<div><icon name='g-filter-none' scale='2'></icon><br>g-filter-none</div>
<div><icon name='g-filter-tilt-shift' scale='2'></icon><br>g-filter-tilt-shift</div>
<div><icon name='g-filter-vintage' scale='2'></icon><br>g-filter-vintage</div>
<div><icon name='g-find-in-page' scale='2'></icon><br>g-find-in-page</div>
<div><icon name='g-find-replace' scale='2'></icon><br>g-find-replace</div>
<div><icon name='g-fingerprint' scale='2'></icon><br>g-fingerprint</div>
<div><icon name='g-first-page' scale='2'></icon><br>g-first-page</div>
<div><icon name='g-fitness-center' scale='2'></icon><br>g-fitness-center</div>
<div><icon name='g-flag' scale='2'></icon><br>g-flag</div>
<div><icon name='g-flare' scale='2'></icon><br>g-flare</div>
<div><icon name='g-flash-auto' scale='2'></icon><br>g-flash-auto</div>
<div><icon name='g-flash-off' scale='2'></icon><br>g-flash-off</div>
<div><icon name='g-flash-on' scale='2'></icon><br>g-flash-on</div>
<div><icon name='g-flight' scale='2'></icon><br>g-flight</div>
<div><icon name='g-flight-land' scale='2'></icon><br>g-flight-land</div>
<div><icon name='g-flight-takeoff' scale='2'></icon><br>g-flight-takeoff</div>
<div><icon name='g-flip' scale='2'></icon><br>g-flip</div>
<div><icon name='g-flip-to-back' scale='2'></icon><br>g-flip-to-back</div>
<div><icon name='g-flip-to-front' scale='2'></icon><br>g-flip-to-front</div>
<div><icon name='g-folder' scale='2'></icon><br>g-folder</div>
<div><icon name='g-folder-open' scale='2'></icon><br>g-folder-open</div>
<div><icon name='g-folder-shared' scale='2'></icon><br>g-folder-shared</div>
<div><icon name='g-folder-special' scale='2'></icon><br>g-folder-special</div>
<div><icon name='g-font-download' scale='2'></icon><br>g-font-download</div>
<div><icon name='g-format-align-center' scale='2'></icon><br>g-format-align-center</div>
<div><icon name='g-format-align-justify' scale='2'></icon><br>g-format-align-justify</div>
<div><icon name='g-format-align-left' scale='2'></icon><br>g-format-align-left</div>
<div><icon name='g-format-align-right' scale='2'></icon><br>g-format-align-right</div>
<div><icon name='g-format-bold' scale='2'></icon><br>g-format-bold</div>
<div><icon name='g-format-clear' scale='2'></icon><br>g-format-clear</div>
<div><icon name='g-format-color-fill' scale='2'></icon><br>g-format-color-fill</div>
<div><icon name='g-format-color-reset' scale='2'></icon><br>g-format-color-reset</div>
<div><icon name='g-format-color-text' scale='2'></icon><br>g-format-color-text</div>
<div><icon name='g-format-indent-decrease' scale='2'></icon><br>g-format-indent-decrease</div>
<div><icon name='g-format-indent-increase' scale='2'></icon><br>g-format-indent-increase</div>
<div><icon name='g-format-italic' scale='2'></icon><br>g-format-italic</div>
<div><icon name='g-format-line-spacing' scale='2'></icon><br>g-format-line-spacing</div>
<div><icon name='g-format-list-bulleted' scale='2'></icon><br>g-format-list-bulleted</div>
<div><icon name='g-format-list-numbered' scale='2'></icon><br>g-format-list-numbered</div>
<div><icon name='g-format-paint' scale='2'></icon><br>g-format-paint</div>
<div><icon name='g-format-quote' scale='2'></icon><br>g-format-quote</div>
<div><icon name='g-format-shapes' scale='2'></icon><br>g-format-shapes</div>
<div><icon name='g-format-size' scale='2'></icon><br>g-format-size</div>
<div><icon name='g-format-strikethrough' scale='2'></icon><br>g-format-strikethrough</div>
<div><icon name='g-format-textdirection-l-to-r' scale='2'></icon><br>g-format-textdirection-l-to-r</div>
<div><icon name='g-format-textdirection-r-to-l' scale='2'></icon><br>g-format-textdirection-r-to-l</div>
<div><icon name='g-format-underline' scale='2'></icon><br>g-format-underline</div>
<div><icon name='g-format-underlined' scale='2'></icon><br>g-format-underlined</div>
<div><icon name='g-forum' scale='2'></icon><br>g-forum</div>
<div><icon name='g-forward-10' scale='2'></icon><br>g-forward-10</div>
<div><icon name='g-forward' scale='2'></icon><br>g-forward</div>
<div><icon name='g-forward-30' scale='2'></icon><br>g-forward-30</div>
<div><icon name='g-forward-5' scale='2'></icon><br>g-forward-5</div>
<div><icon name='g-free-breakfast' scale='2'></icon><br>g-free-breakfast</div>
<div><icon name='g-fullscreen' scale='2'></icon><br>g-fullscreen</div>
<div><icon name='g-fullscreen-exit' scale='2'></icon><br>g-fullscreen-exit</div>
<div><icon name='g-functions' scale='2'></icon><br>g-functions</div>
<div><icon name='g-g-translate' scale='2'></icon><br>g-g-translate</div>
<div><icon name='g-gamepad' scale='2'></icon><br>g-gamepad</div>
<div><icon name='g-games' scale='2'></icon><br>g-games</div>
<div><icon name='g-gavel' scale='2'></icon><br>g-gavel</div>
<div><icon name='g-gesture' scale='2'></icon><br>g-gesture</div>
<div><icon name='g-get-app' scale='2'></icon><br>g-get-app</div>
<div><icon name='g-gif' scale='2'></icon><br>g-gif</div>
<div><icon name='g-golf-course' scale='2'></icon><br>g-golf-course</div>
<div><icon name='g-gps-fixed' scale='2'></icon><br>g-gps-fixed</div>
<div><icon name='g-gps-not-fixed' scale='2'></icon><br>g-gps-not-fixed</div>
<div><icon name='g-gps-off' scale='2'></icon><br>g-gps-off</div>
<div><icon name='g-grade' scale='2'></icon><br>g-grade</div>
<div><icon name='g-gradient' scale='2'></icon><br>g-gradient</div>
<div><icon name='g-grain' scale='2'></icon><br>g-grain</div>
<div><icon name='g-graphic-eq' scale='2'></icon><br>g-graphic-eq</div>
<div><icon name='g-grid-off' scale='2'></icon><br>g-grid-off</div>
<div><icon name='g-grid-on' scale='2'></icon><br>g-grid-on</div>
<div><icon name='g-group' scale='2'></icon><br>g-group</div>
<div><icon name='g-group-add' scale='2'></icon><br>g-group-add</div>
<div><icon name='g-group-work' scale='2'></icon><br>g-group-work</div>
<div><icon name='g-hd' scale='2'></icon><br>g-hd</div>
<div><icon name='g-hdr-off' scale='2'></icon><br>g-hdr-off</div>
<div><icon name='g-hdr-on' scale='2'></icon><br>g-hdr-on</div>
<div><icon name='g-hdr-strong' scale='2'></icon><br>g-hdr-strong</div>
<div><icon name='g-hdr-weak' scale='2'></icon><br>g-hdr-weak</div>
<div><icon name='g-headset' scale='2'></icon><br>g-headset</div>
<div><icon name='g-headset-mic' scale='2'></icon><br>g-headset-mic</div>
<div><icon name='g-healing' scale='2'></icon><br>g-healing</div>
<div><icon name='g-hearing' scale='2'></icon><br>g-hearing</div>
<div><icon name='g-help' scale='2'></icon><br>g-help</div>
<div><icon name='g-help-outline' scale='2'></icon><br>g-help-outline</div>
<div><icon name='g-high-quality' scale='2'></icon><br>g-high-quality</div>
<div><icon name='g-highlight' scale='2'></icon><br>g-highlight</div>
<div><icon name='g-highlight-off' scale='2'></icon><br>g-highlight-off</div>
<div><icon name='g-highlight-remove' scale='2'></icon><br>g-highlight-remove</div>
<div><icon name='g-history' scale='2'></icon><br>g-history</div>
<div><icon name='g-home' scale='2'></icon><br>g-home</div>
<div><icon name='g-hot-tub' scale='2'></icon><br>g-hot-tub</div>
<div><icon name='g-hotel' scale='2'></icon><br>g-hotel</div>
<div><icon name='g-hourglass-empty' scale='2'></icon><br>g-hourglass-empty</div>
<div><icon name='g-hourglass-full' scale='2'></icon><br>g-hourglass-full</div>
<div><icon name='g-http' scale='2'></icon><br>g-http</div>
<div><icon name='g-https' scale='2'></icon><br>g-https</div>
<div><icon name='g-image' scale='2'></icon><br>g-image</div>
<div><icon name='g-image-aspect-ratio' scale='2'></icon><br>g-image-aspect-ratio</div>
<div><icon name='g-import-contacts' scale='2'></icon><br>g-import-contacts</div>
<div><icon name='g-import-export' scale='2'></icon><br>g-import-export</div>
<div><icon name='g-important-devices' scale='2'></icon><br>g-important-devices</div>
<div><icon name='g-inbox' scale='2'></icon><br>g-inbox</div>
<div><icon name='g-indeterminate-check-box' scale='2'></icon><br>g-indeterminate-check-box</div>
<div><icon name='g-info' scale='2'></icon><br>g-info</div>
<div><icon name='g-info-outline' scale='2'></icon><br>g-info-outline</div>
<div><icon name='g-input' scale='2'></icon><br>g-input</div>
<div><icon name='g-insert-chart' scale='2'></icon><br>g-insert-chart</div>
<div><icon name='g-insert-comment' scale='2'></icon><br>g-insert-comment</div>
<div><icon name='g-insert-drive-file' scale='2'></icon><br>g-insert-drive-file</div>
<div><icon name='g-insert-emoticon' scale='2'></icon><br>g-insert-emoticon</div>
<div><icon name='g-insert-invitation' scale='2'></icon><br>g-insert-invitation</div>
<div><icon name='g-insert-link' scale='2'></icon><br>g-insert-link</div>
<div><icon name='g-insert-photo' scale='2'></icon><br>g-insert-photo</div>
<div><icon name='g-invert-colors' scale='2'></icon><br>g-invert-colors</div>
<div><icon name='g-invert-colors-off' scale='2'></icon><br>g-invert-colors-off</div>
<div><icon name='g-invert-colors-on' scale='2'></icon><br>g-invert-colors-on</div>
<div><icon name='g-iso' scale='2'></icon><br>g-iso</div>
<div><icon name='g-keyboard' scale='2'></icon><br>g-keyboard</div>
<div><icon name='g-keyboard-alt' scale='2'></icon><br>g-keyboard-alt</div>
<div><icon name='g-keyboard-arrow-down' scale='2'></icon><br>g-keyboard-arrow-down</div>
<div><icon name='g-keyboard-arrow-left' scale='2'></icon><br>g-keyboard-arrow-left</div>
<div><icon name='g-keyboard-arrow-right' scale='2'></icon><br>g-keyboard-arrow-right</div>
<div><icon name='g-keyboard-arrow-up' scale='2'></icon><br>g-keyboard-arrow-up</div>
<div><icon name='g-keyboard-backspace' scale='2'></icon><br>g-keyboard-backspace</div>
<div><icon name='g-keyboard-capslock' scale='2'></icon><br>g-keyboard-capslock</div>
<div><icon name='g-keyboard-control' scale='2'></icon><br>g-keyboard-control</div>
<div><icon name='g-keyboard-hide' scale='2'></icon><br>g-keyboard-hide</div>
<div><icon name='g-keyboard-return' scale='2'></icon><br>g-keyboard-return</div>
<div><icon name='g-keyboard-tab' scale='2'></icon><br>g-keyboard-tab</div>
<div><icon name='g-keyboard-voice' scale='2'></icon><br>g-keyboard-voice</div>
<div><icon name='g-kitchen' scale='2'></icon><br>g-kitchen</div>
<div><icon name='g-label' scale='2'></icon><br>g-label</div>
<div><icon name='g-label-outline' scale='2'></icon><br>g-label-outline</div>
<div><icon name='g-landscape' scale='2'></icon><br>g-landscape</div>
<div><icon name='g-language' scale='2'></icon><br>g-language</div>
<div><icon name='g-laptop' scale='2'></icon><br>g-laptop</div>
<div><icon name='g-laptop-chromebook' scale='2'></icon><br>g-laptop-chromebook</div>
<div><icon name='g-laptop-mac' scale='2'></icon><br>g-laptop-mac</div>
<div><icon name='g-laptop-windows' scale='2'></icon><br>g-laptop-windows</div>
<div><icon name='g-last-page' scale='2'></icon><br>g-last-page</div>
<div><icon name='g-launch' scale='2'></icon><br>g-launch</div>
<div><icon name='g-layers' scale='2'></icon><br>g-layers</div>
<div><icon name='g-layers-clear' scale='2'></icon><br>g-layers-clear</div>
<div><icon name='g-leak-add' scale='2'></icon><br>g-leak-add</div>
<div><icon name='g-leak-remove' scale='2'></icon><br>g-leak-remove</div>
<div><icon name='g-lens' scale='2'></icon><br>g-lens</div>
<div><icon name='g-library-add' scale='2'></icon><br>g-library-add</div>
<div><icon name='g-library-books' scale='2'></icon><br>g-library-books</div>
<div><icon name='g-library-music' scale='2'></icon><br>g-library-music</div>
<div><icon name='g-lightbulb-outline' scale='2'></icon><br>g-lightbulb-outline</div>
<div><icon name='g-line-style' scale='2'></icon><br>g-line-style</div>
<div><icon name='g-line-weight' scale='2'></icon><br>g-line-weight</div>
<div><icon name='g-linear-scale' scale='2'></icon><br>g-linear-scale</div>
<div><icon name='g-link' scale='2'></icon><br>g-link</div>
<div><icon name='g-linked-camera' scale='2'></icon><br>g-linked-camera</div>
<div><icon name='g-list' scale='2'></icon><br>g-list</div>
<div><icon name='g-live-help' scale='2'></icon><br>g-live-help</div>
<div><icon name='g-live-tv' scale='2'></icon><br>g-live-tv</div>
<div><icon name='g-local-activity' scale='2'></icon><br>g-local-activity</div>
<div><icon name='g-local-airport' scale='2'></icon><br>g-local-airport</div>
<div><icon name='g-local-atm' scale='2'></icon><br>g-local-atm</div>
<div><icon name='g-local-attraction' scale='2'></icon><br>g-local-attraction</div>
<div><icon name='g-local-bar' scale='2'></icon><br>g-local-bar</div>
<div><icon name='g-local-cafe' scale='2'></icon><br>g-local-cafe</div>
<div><icon name='g-local-car-wash' scale='2'></icon><br>g-local-car-wash</div>
<div><icon name='g-local-convenience-store' scale='2'></icon><br>g-local-convenience-store</div>
<div><icon name='g-local-dining' scale='2'></icon><br>g-local-dining</div>
<div><icon name='g-local-drink' scale='2'></icon><br>g-local-drink</div>
<div><icon name='g-local-florist' scale='2'></icon><br>g-local-florist</div>
<div><icon name='g-local-gas-station' scale='2'></icon><br>g-local-gas-station</div>
<div><icon name='g-local-grocery-store' scale='2'></icon><br>g-local-grocery-store</div>
<div><icon name='g-local-hospital' scale='2'></icon><br>g-local-hospital</div>
<div><icon name='g-local-hotel' scale='2'></icon><br>g-local-hotel</div>
<div><icon name='g-local-laundry-service' scale='2'></icon><br>g-local-laundry-service</div>
<div><icon name='g-local-library' scale='2'></icon><br>g-local-library</div>
<div><icon name='g-local-mall' scale='2'></icon><br>g-local-mall</div>
<div><icon name='g-local-movies' scale='2'></icon><br>g-local-movies</div>
<div><icon name='g-local-offer' scale='2'></icon><br>g-local-offer</div>
<div><icon name='g-local-parking' scale='2'></icon><br>g-local-parking</div>
<div><icon name='g-local-pharmacy' scale='2'></icon><br>g-local-pharmacy</div>
<div><icon name='g-local-phone' scale='2'></icon><br>g-local-phone</div>
<div><icon name='g-local-pizza' scale='2'></icon><br>g-local-pizza</div>
<div><icon name='g-local-play' scale='2'></icon><br>g-local-play</div>
<div><icon name='g-local-post-office' scale='2'></icon><br>g-local-post-office</div>
<div><icon name='g-local-print-shop' scale='2'></icon><br>g-local-print-shop</div>
<div><icon name='g-local-printshop' scale='2'></icon><br>g-local-printshop</div>
<div><icon name='g-local-restaurant' scale='2'></icon><br>g-local-restaurant</div>
<div><icon name='g-local-see' scale='2'></icon><br>g-local-see</div>
<div><icon name='g-local-shipping' scale='2'></icon><br>g-local-shipping</div>
<div><icon name='g-local-taxi' scale='2'></icon><br>g-local-taxi</div>
<div><icon name='g-location-city' scale='2'></icon><br>g-location-city</div>
<div><icon name='g-location-disabled' scale='2'></icon><br>g-location-disabled</div>
<div><icon name='g-location-history' scale='2'></icon><br>g-location-history</div>
<div><icon name='g-location-off' scale='2'></icon><br>g-location-off</div>
<div><icon name='g-location-on' scale='2'></icon><br>g-location-on</div>
<div><icon name='g-location-searching' scale='2'></icon><br>g-location-searching</div>
<div><icon name='g-lock' scale='2'></icon><br>g-lock</div>
<div><icon name='g-lock-open' scale='2'></icon><br>g-lock-open</div>
<div><icon name='g-lock-outline' scale='2'></icon><br>g-lock-outline</div>
<div><icon name='g-looks' scale='2'></icon><br>g-looks</div>
<div><icon name='g-looks-3' scale='2'></icon><br>g-looks-3</div>
<div><icon name='g-looks-4' scale='2'></icon><br>g-looks-4</div>
<div><icon name='g-looks-5' scale='2'></icon><br>g-looks-5</div>
<div><icon name='g-looks-6' scale='2'></icon><br>g-looks-6</div>
<div><icon name='g-looks-one' scale='2'></icon><br>g-looks-one</div>
<div><icon name='g-looks-two' scale='2'></icon><br>g-looks-two</div>
<div><icon name='g-loop' scale='2'></icon><br>g-loop</div>
<div><icon name='g-loupe' scale='2'></icon><br>g-loupe</div>
<div><icon name='g-low-priority' scale='2'></icon><br>g-low-priority</div>
<div><icon name='g-loyalty' scale='2'></icon><br>g-loyalty</div>
<div><icon name='g-mail' scale='2'></icon><br>g-mail</div>
<div><icon name='g-mail-outline' scale='2'></icon><br>g-mail-outline</div>
<div><icon name='g-map' scale='2'></icon><br>g-map</div>
<div><icon name='g-markunread' scale='2'></icon><br>g-markunread</div>
<div><icon name='g-markunread-mailbox' scale='2'></icon><br>g-markunread-mailbox</div>
<div><icon name='g-memory' scale='2'></icon><br>g-memory</div>
<div><icon name='g-menu' scale='2'></icon><br>g-menu</div>
<div><icon name='g-merge-type' scale='2'></icon><br>g-merge-type</div>
<div><icon name='g-message' scale='2'></icon><br>g-message</div>
<div><icon name='g-messenger' scale='2'></icon><br>g-messenger</div>
<div><icon name='g-mic' scale='2'></icon><br>g-mic</div>
<div><icon name='g-mic-none' scale='2'></icon><br>g-mic-none</div>
<div><icon name='g-mic-off' scale='2'></icon><br>g-mic-off</div>
<div><icon name='g-mms' scale='2'></icon><br>g-mms</div>
<div><icon name='g-mode-comment' scale='2'></icon><br>g-mode-comment</div>
<div><icon name='g-mode-edit' scale='2'></icon><br>g-mode-edit</div>
<div><icon name='g-monetization-on' scale='2'></icon><br>g-monetization-on</div>
<div><icon name='g-money-off' scale='2'></icon><br>g-money-off</div>
<div><icon name='g-monochrome-photos' scale='2'></icon><br>g-monochrome-photos</div>
<div><icon name='g-mood' scale='2'></icon><br>g-mood</div>
<div><icon name='g-mood-bad' scale='2'></icon><br>g-mood-bad</div>
<div><icon name='g-more' scale='2'></icon><br>g-more</div>
<div><icon name='g-more-horiz' scale='2'></icon><br>g-more-horiz</div>
<div><icon name='g-more-vert' scale='2'></icon><br>g-more-vert</div>
<div><icon name='g-motorcycle' scale='2'></icon><br>g-motorcycle</div>
<div><icon name='g-mouse' scale='2'></icon><br>g-mouse</div>
<div><icon name='g-move-to-inbox' scale='2'></icon><br>g-move-to-inbox</div>
<div><icon name='g-movie' scale='2'></icon><br>g-movie</div>
<div><icon name='g-movie-creation' scale='2'></icon><br>g-movie-creation</div>
<div><icon name='g-movie-filter' scale='2'></icon><br>g-movie-filter</div>
<div><icon name='g-multiline-chart' scale='2'></icon><br>g-multiline-chart</div>
<div><icon name='g-multitrack-audio' scale='2'></icon><br>g-multitrack-audio</div>
<div><icon name='g-music-note' scale='2'></icon><br>g-music-note</div>
<div><icon name='g-music-video' scale='2'></icon><br>g-music-video</div>
<div><icon name='g-my-library-add' scale='2'></icon><br>g-my-library-add</div>
<div><icon name='g-my-library-books' scale='2'></icon><br>g-my-library-books</div>
<div><icon name='g-my-library-music' scale='2'></icon><br>g-my-library-music</div>
<div><icon name='g-my-location' scale='2'></icon><br>g-my-location</div>
<div><icon name='g-nature' scale='2'></icon><br>g-nature</div>
<div><icon name='g-nature-people' scale='2'></icon><br>g-nature-people</div>
<div><icon name='g-navigate-before' scale='2'></icon><br>g-navigate-before</div>
<div><icon name='g-navigate-next' scale='2'></icon><br>g-navigate-next</div>
<div><icon name='g-navigation' scale='2'></icon><br>g-navigation</div>
<div><icon name='g-near-me' scale='2'></icon><br>g-near-me</div>
<div><icon name='g-network-cell' scale='2'></icon><br>g-network-cell</div>
<div><icon name='g-network-check' scale='2'></icon><br>g-network-check</div>
<div><icon name='g-network-locked' scale='2'></icon><br>g-network-locked</div>
<div><icon name='g-network-wifi' scale='2'></icon><br>g-network-wifi</div>
<div><icon name='g-new-releases' scale='2'></icon><br>g-new-releases</div>
<div><icon name='g-next-week' scale='2'></icon><br>g-next-week</div>
<div><icon name='g-nfc' scale='2'></icon><br>g-nfc</div>
<div><icon name='g-no-encryption' scale='2'></icon><br>g-no-encryption</div>
<div><icon name='g-no-sim' scale='2'></icon><br>g-no-sim</div>
<div><icon name='g-not-interested' scale='2'></icon><br>g-not-interested</div>
<div><icon name='g-note' scale='2'></icon><br>g-note</div>
<div><icon name='g-note-add' scale='2'></icon><br>g-note-add</div>
<div><icon name='g-notifications' scale='2'></icon><br>g-notifications</div>
<div><icon name='g-notifications-active' scale='2'></icon><br>g-notifications-active</div>
<div><icon name='g-notifications-none' scale='2'></icon><br>g-notifications-none</div>
<div><icon name='g-notifications-off' scale='2'></icon><br>g-notifications-off</div>
<div><icon name='g-notifications-on' scale='2'></icon><br>g-notifications-on</div>
<div><icon name='g-notifications-paused' scale='2'></icon><br>g-notifications-paused</div>
<div><icon name='g-now-wallpaper' scale='2'></icon><br>g-now-wallpaper</div>
<div><icon name='g-now-widgets' scale='2'></icon><br>g-now-widgets</div>
<div><icon name='g-offline-pin' scale='2'></icon><br>g-offline-pin</div>
<div><icon name='g-ondemand-video' scale='2'></icon><br>g-ondemand-video</div>
<div><icon name='g-opacity' scale='2'></icon><br>g-opacity</div>
<div><icon name='g-open-in-browser' scale='2'></icon><br>g-open-in-browser</div>
<div><icon name='g-open-in-new' scale='2'></icon><br>g-open-in-new</div>
<div><icon name='g-open-with' scale='2'></icon><br>g-open-with</div>
<div><icon name='g-pages' scale='2'></icon><br>g-pages</div>
<div><icon name='g-pageview' scale='2'></icon><br>g-pageview</div>
<div><icon name='g-palette' scale='2'></icon><br>g-palette</div>
<div><icon name='g-pan-tool' scale='2'></icon><br>g-pan-tool</div>
<div><icon name='g-panorama' scale='2'></icon><br>g-panorama</div>
<div><icon name='g-panorama-fish-eye' scale='2'></icon><br>g-panorama-fish-eye</div>
<div><icon name='g-panorama-fisheye' scale='2'></icon><br>g-panorama-fisheye</div>
<div><icon name='g-panorama-horizontal' scale='2'></icon><br>g-panorama-horizontal</div>
<div><icon name='g-panorama-vertical' scale='2'></icon><br>g-panorama-vertical</div>
<div><icon name='g-panorama-wide-angle' scale='2'></icon><br>g-panorama-wide-angle</div>
<div><icon name='g-party-mode' scale='2'></icon><br>g-party-mode</div>
<div><icon name='g-pause' scale='2'></icon><br>g-pause</div>
<div><icon name='g-pause-circle-fill' scale='2'></icon><br>g-pause-circle-fill</div>
<div><icon name='g-pause-circle-filled' scale='2'></icon><br>g-pause-circle-filled</div>
<div><icon name='g-pause-circle-outline' scale='2'></icon><br>g-pause-circle-outline</div>
<div><icon name='g-payment' scale='2'></icon><br>g-payment</div>
<div><icon name='g-people' scale='2'></icon><br>g-people</div>
<div><icon name='g-people-outline' scale='2'></icon><br>g-people-outline</div>
<div><icon name='g-perm-camera-mic' scale='2'></icon><br>g-perm-camera-mic</div>
<div><icon name='g-perm-contact-cal' scale='2'></icon><br>g-perm-contact-cal</div>
<div><icon name='g-perm-contact-calendar' scale='2'></icon><br>g-perm-contact-calendar</div>
<div><icon name='g-perm-data-setting' scale='2'></icon><br>g-perm-data-setting</div>
<div><icon name='g-perm-device-info' scale='2'></icon><br>g-perm-device-info</div>
<div><icon name='g-perm-device-information' scale='2'></icon><br>g-perm-device-information</div>
<div><icon name='g-perm-identity' scale='2'></icon><br>g-perm-identity</div>
<div><icon name='g-perm-media' scale='2'></icon><br>g-perm-media</div>
<div><icon name='g-perm-phone-msg' scale='2'></icon><br>g-perm-phone-msg</div>
<div><icon name='g-perm-scan-wifi' scale='2'></icon><br>g-perm-scan-wifi</div>
<div><icon name='g-person' scale='2'></icon><br>g-person</div>
<div><icon name='g-person-add' scale='2'></icon><br>g-person-add</div>
<div><icon name='g-person-outline' scale='2'></icon><br>g-person-outline</div>
<div><icon name='g-person-pin' scale='2'></icon><br>g-person-pin</div>
<div><icon name='g-person-pin-circle' scale='2'></icon><br>g-person-pin-circle</div>
<div><icon name='g-personal-video' scale='2'></icon><br>g-personal-video</div>
<div><icon name='g-pets' scale='2'></icon><br>g-pets</div>
<div><icon name='g-phone' scale='2'></icon><br>g-phone</div>
<div><icon name='g-phone-android' scale='2'></icon><br>g-phone-android</div>
<div><icon name='g-phone-bluetooth-speaker' scale='2'></icon><br>g-phone-bluetooth-speaker</div>
<div><icon name='g-phone-forwarded' scale='2'></icon><br>g-phone-forwarded</div>
<div><icon name='g-phone-in-talk' scale='2'></icon><br>g-phone-in-talk</div>
<div><icon name='g-phone-iphone' scale='2'></icon><br>g-phone-iphone</div>
<div><icon name='g-phone-locked' scale='2'></icon><br>g-phone-locked</div>
<div><icon name='g-phone-missed' scale='2'></icon><br>g-phone-missed</div>
<div><icon name='g-phone-paused' scale='2'></icon><br>g-phone-paused</div>
<div><icon name='g-phonelink' scale='2'></icon><br>g-phonelink</div>
<div><icon name='g-phonelink-erase' scale='2'></icon><br>g-phonelink-erase</div>
<div><icon name='g-phonelink-lock' scale='2'></icon><br>g-phonelink-lock</div>
<div><icon name='g-phonelink-off' scale='2'></icon><br>g-phonelink-off</div>
<div><icon name='g-phonelink-ring' scale='2'></icon><br>g-phonelink-ring</div>
<div><icon name='g-phonelink-setup' scale='2'></icon><br>g-phonelink-setup</div>
<div><icon name='g-photo' scale='2'></icon><br>g-photo</div>
<div><icon name='g-photo-album' scale='2'></icon><br>g-photo-album</div>
<div><icon name='g-photo-camera' scale='2'></icon><br>g-photo-camera</div>
<div><icon name='g-photo-filter' scale='2'></icon><br>g-photo-filter</div>
<div><icon name='g-photo-library' scale='2'></icon><br>g-photo-library</div>
<div><icon name='g-photo-size-select-actual' scale='2'></icon><br>g-photo-size-select-actual</div>
<div><icon name='g-photo-size-select-large' scale='2'></icon><br>g-photo-size-select-large</div>
<div><icon name='g-photo-size-select-small' scale='2'></icon><br>g-photo-size-select-small</div>
<div><icon name='g-picture-as-pdf' scale='2'></icon><br>g-picture-as-pdf</div>
<div><icon name='g-picture-in-picture' scale='2'></icon><br>g-picture-in-picture</div>
<div><icon name='g-picture-in-picture-alt' scale='2'></icon><br>g-picture-in-picture-alt</div>
<div><icon name='g-pie-chart' scale='2'></icon><br>g-pie-chart</div>
<div><icon name='g-pie-chart-outlined' scale='2'></icon><br>g-pie-chart-outlined</div>
<div><icon name='g-pin-drop' scale='2'></icon><br>g-pin-drop</div>
<div><icon name='g-place' scale='2'></icon><br>g-place</div>
<div><icon name='g-play-arrow' scale='2'></icon><br>g-play-arrow</div>
<div><icon name='g-play-circle-fill' scale='2'></icon><br>g-play-circle-fill</div>
<div><icon name='g-play-circle-filled' scale='2'></icon><br>g-play-circle-filled</div>
<div><icon name='g-play-circle-outline' scale='2'></icon><br>g-play-circle-outline</div>
<div><icon name='g-play-download' scale='2'></icon><br>g-play-download</div>
<div><icon name='g-play-for-work' scale='2'></icon><br>g-play-for-work</div>
<div><icon name='g-play-install' scale='2'></icon><br>g-play-install</div>
<div><icon name='g-play-shopping-bag' scale='2'></icon><br>g-play-shopping-bag</div>
<div><icon name='g-playlist-add' scale='2'></icon><br>g-playlist-add</div>
<div><icon name='g-playlist-add-check' scale='2'></icon><br>g-playlist-add-check</div>
<div><icon name='g-plus-one' scale='2'></icon><br>g-plus-one</div>
<div><icon name='g-poll' scale='2'></icon><br>g-poll</div>
<div><icon name='g-polymer' scale='2'></icon><br>g-polymer</div>
<div><icon name='g-pool' scale='2'></icon><br>g-pool</div>
<div><icon name='g-portable-wifi-off' scale='2'></icon><br>g-portable-wifi-off</div>
<div><icon name='g-portrait' scale='2'></icon><br>g-portrait</div>
<div><icon name='g-power' scale='2'></icon><br>g-power</div>
<div><icon name='g-power-input' scale='2'></icon><br>g-power-input</div>
<div><icon name='g-power-settings-new' scale='2'></icon><br>g-power-settings-new</div>
<div><icon name='g-pregnant-woman' scale='2'></icon><br>g-pregnant-woman</div>
<div><icon name='g-present-to-all' scale='2'></icon><br>g-present-to-all</div>
<div><icon name='g-print' scale='2'></icon><br>g-print</div>
<div><icon name='g-priority-high' scale='2'></icon><br>g-priority-high</div>
<div><icon name='g-public' scale='2'></icon><br>g-public</div>
<div><icon name='g-publish' scale='2'></icon><br>g-publish</div>
<div><icon name='g-query-builder' scale='2'></icon><br>g-query-builder</div>
<div><icon name='g-question-answer' scale='2'></icon><br>g-question-answer</div>
<div><icon name='g-queue' scale='2'></icon><br>g-queue</div>
<div><icon name='g-queue-music' scale='2'></icon><br>g-queue-music</div>
<div><icon name='g-queue-play-next' scale='2'></icon><br>g-queue-play-next</div>
<div><icon name='g-quick-contacts-dialer' scale='2'></icon><br>g-quick-contacts-dialer</div>
<div><icon name='g-quick-contacts-mail' scale='2'></icon><br>g-quick-contacts-mail</div>
<div><icon name='g-radio' scale='2'></icon><br>g-radio</div>
<div><icon name='g-radio-button-checked' scale='2'></icon><br>g-radio-button-checked</div>
<div><icon name='g-radio-button-off' scale='2'></icon><br>g-radio-button-off</div>
<div><icon name='g-radio-button-on' scale='2'></icon><br>g-radio-button-on</div>
<div><icon name='g-radio-button-unchecked' scale='2'></icon><br>g-radio-button-unchecked</div>
<div><icon name='g-rate-review' scale='2'></icon><br>g-rate-review</div>
<div><icon name='g-receipt' scale='2'></icon><br>g-receipt</div>
<div><icon name='g-recent-actors' scale='2'></icon><br>g-recent-actors</div>
<div><icon name='g-record-voice-over' scale='2'></icon><br>g-record-voice-over</div>
<div><icon name='g-redeem' scale='2'></icon><br>g-redeem</div>
<div><icon name='g-redo' scale='2'></icon><br>g-redo</div>
<div><icon name='g-refresh' scale='2'></icon><br>g-refresh</div>
<div><icon name='g-remove' scale='2'></icon><br>g-remove</div>
<div><icon name='g-remove-circle' scale='2'></icon><br>g-remove-circle</div>
<div><icon name='g-remove-circle-outline' scale='2'></icon><br>g-remove-circle-outline</div>
<div><icon name='g-remove-from-queue' scale='2'></icon><br>g-remove-from-queue</div>
<div><icon name='g-remove-red-eye' scale='2'></icon><br>g-remove-red-eye</div>
<div><icon name='g-remove-shopping-cart' scale='2'></icon><br>g-remove-shopping-cart</div>
<div><icon name='g-reorder' scale='2'></icon><br>g-reorder</div>
<div><icon name='g-repeat' scale='2'></icon><br>g-repeat</div>
<div><icon name='g-repeat-one' scale='2'></icon><br>g-repeat-one</div>
<div><icon name='g-replay-10' scale='2'></icon><br>g-replay-10</div>
<div><icon name='g-replay' scale='2'></icon><br>g-replay</div>
<div><icon name='g-replay-30' scale='2'></icon><br>g-replay-30</div>
<div><icon name='g-replay-5' scale='2'></icon><br>g-replay-5</div>
<div><icon name='g-reply' scale='2'></icon><br>g-reply</div>
<div><icon name='g-reply-all' scale='2'></icon><br>g-reply-all</div>
<div><icon name='g-report' scale='2'></icon><br>g-report</div>
<div><icon name='g-report-problem' scale='2'></icon><br>g-report-problem</div>
<div><icon name='g-restaurant' scale='2'></icon><br>g-restaurant</div>
<div><icon name='g-restaurant-menu' scale='2'></icon><br>g-restaurant-menu</div>
<div><icon name='g-restore' scale='2'></icon><br>g-restore</div>
<div><icon name='g-restore-page' scale='2'></icon><br>g-restore-page</div>
<div><icon name='g-ring-volume' scale='2'></icon><br>g-ring-volume</div>
<div><icon name='g-room' scale='2'></icon><br>g-room</div>
<div><icon name='g-room-service' scale='2'></icon><br>g-room-service</div>
<div><icon name='g-rotate-90-degrees-ccw' scale='2'></icon><br>g-rotate-90-degrees-ccw</div>
<div><icon name='g-rotate-left' scale='2'></icon><br>g-rotate-left</div>
<div><icon name='g-rotate-right' scale='2'></icon><br>g-rotate-right</div>
<div><icon name='g-rounded-corner' scale='2'></icon><br>g-rounded-corner</div>
<div><icon name='g-router' scale='2'></icon><br>g-router</div>
<div><icon name='g-rowing' scale='2'></icon><br>g-rowing</div>
<div><icon name='g-rss-feed' scale='2'></icon><br>g-rss-feed</div>
<div><icon name='g-rv-hookup' scale='2'></icon><br>g-rv-hookup</div>
<div><icon name='g-satellite' scale='2'></icon><br>g-satellite</div>
<div><icon name='g-save' scale='2'></icon><br>g-save</div>
<div><icon name='g-scanner' scale='2'></icon><br>g-scanner</div>
<div><icon name='g-schedule' scale='2'></icon><br>g-schedule</div>
<div><icon name='g-school' scale='2'></icon><br>g-school</div>
<div><icon name='g-screen-lock-landscape' scale='2'></icon><br>g-screen-lock-landscape</div>
<div><icon name='g-screen-lock-portrait' scale='2'></icon><br>g-screen-lock-portrait</div>
<div><icon name='g-screen-lock-rotation' scale='2'></icon><br>g-screen-lock-rotation</div>
<div><icon name='g-screen-rotation' scale='2'></icon><br>g-screen-rotation</div>
<div><icon name='g-screen-share' scale='2'></icon><br>g-screen-share</div>
<div><icon name='g-sd-card' scale='2'></icon><br>g-sd-card</div>
<div><icon name='g-sd-storage' scale='2'></icon><br>g-sd-storage</div>
<div><icon name='g-search' scale='2'></icon><br>g-search</div>
<div><icon name='g-security' scale='2'></icon><br>g-security</div>
<div><icon name='g-select-all' scale='2'></icon><br>g-select-all</div>
<div><icon name='g-send' scale='2'></icon><br>g-send</div>
<div><icon name='g-sentiment-dissatisfied' scale='2'></icon><br>g-sentiment-dissatisfied</div>
<div><icon name='g-sentiment-neutral' scale='2'></icon><br>g-sentiment-neutral</div>
<div><icon name='g-sentiment-satisfied' scale='2'></icon><br>g-sentiment-satisfied</div>
<div><icon name='g-sentiment-very-dissatisfied' scale='2'></icon><br>g-sentiment-very-dissatisfied</div>
<div><icon name='g-sentiment-very-satisfied' scale='2'></icon><br>g-sentiment-very-satisfied</div>
<div><icon name='g-settings' scale='2'></icon><br>g-settings</div>
<div><icon name='g-settings-applications' scale='2'></icon><br>g-settings-applications</div>
<div><icon name='g-settings-backup-restore' scale='2'></icon><br>g-settings-backup-restore</div>
<div><icon name='g-settings-bluetooth' scale='2'></icon><br>g-settings-bluetooth</div>
<div><icon name='g-settings-brightness' scale='2'></icon><br>g-settings-brightness</div>
<div><icon name='g-settings-cell' scale='2'></icon><br>g-settings-cell</div>
<div><icon name='g-settings-display' scale='2'></icon><br>g-settings-display</div>
<div><icon name='g-settings-ethernet' scale='2'></icon><br>g-settings-ethernet</div>
<div><icon name='g-settings-input-antenna' scale='2'></icon><br>g-settings-input-antenna</div>
<div><icon name='g-settings-input-component' scale='2'></icon><br>g-settings-input-component</div>
<div><icon name='g-settings-input-composite' scale='2'></icon><br>g-settings-input-composite</div>
<div><icon name='g-settings-input-hdmi' scale='2'></icon><br>g-settings-input-hdmi</div>
<div><icon name='g-settings-input-svideo' scale='2'></icon><br>g-settings-input-svideo</div>
<div><icon name='g-settings-overscan' scale='2'></icon><br>g-settings-overscan</div>
<div><icon name='g-settings-phone' scale='2'></icon><br>g-settings-phone</div>
<div><icon name='g-settings-power' scale='2'></icon><br>g-settings-power</div>
<div><icon name='g-settings-remote' scale='2'></icon><br>g-settings-remote</div>
<div><icon name='g-settings-system-daydream' scale='2'></icon><br>g-settings-system-daydream</div>
<div><icon name='g-settings-voice' scale='2'></icon><br>g-settings-voice</div>
<div><icon name='g-share' scale='2'></icon><br>g-share</div>
<div><icon name='g-shop' scale='2'></icon><br>g-shop</div>
<div><icon name='g-shop-two' scale='2'></icon><br>g-shop-two</div>
<div><icon name='g-shopping-basket' scale='2'></icon><br>g-shopping-basket</div>
<div><icon name='g-shopping-cart' scale='2'></icon><br>g-shopping-cart</div>
<div><icon name='g-short-text' scale='2'></icon><br>g-short-text</div>
<div><icon name='g-show-chart' scale='2'></icon><br>g-show-chart</div>
<div><icon name='g-shuffle' scale='2'></icon><br>g-shuffle</div>
<div><icon name='g-signal-cellular-0-bar' scale='2'></icon><br>g-signal-cellular-0-bar</div>
<div><icon name='g-signal-cellular-1-bar' scale='2'></icon><br>g-signal-cellular-1-bar</div>
<div><icon name='g-signal-cellular-2-bar' scale='2'></icon><br>g-signal-cellular-2-bar</div>
<div><icon name='g-signal-cellular-3-bar' scale='2'></icon><br>g-signal-cellular-3-bar</div>
<div><icon name='g-signal-cellular-4-bar' scale='2'></icon><br>g-signal-cellular-4-bar</div>
<div><icon name='g-signal-cellular-connected-no-internet-0-bar' scale='2'></icon><br>g-signal-cellular-connected-no-internet-0-bar</div>
<div><icon name='g-signal-cellular-connected-no-internet-1-bar' scale='2'></icon><br>g-signal-cellular-connected-no-internet-1-bar</div>
<div><icon name='g-signal-cellular-connected-no-internet-2-bar' scale='2'></icon><br>g-signal-cellular-connected-no-internet-2-bar</div>
<div><icon name='g-signal-cellular-connected-no-internet-3-bar' scale='2'></icon><br>g-signal-cellular-connected-no-internet-3-bar</div>
<div><icon name='g-signal-cellular-connected-no-internet-4-bar' scale='2'></icon><br>g-signal-cellular-connected-no-internet-4-bar</div>
<div><icon name='g-signal-cellular-no-sim' scale='2'></icon><br>g-signal-cellular-no-sim</div>
<div><icon name='g-signal-cellular-null' scale='2'></icon><br>g-signal-cellular-null</div>
<div><icon name='g-signal-cellular-off' scale='2'></icon><br>g-signal-cellular-off</div>
<div><icon name='g-signal-wifi-0-bar' scale='2'></icon><br>g-signal-wifi-0-bar</div>
<div><icon name='g-signal-wifi-1-bar' scale='2'></icon><br>g-signal-wifi-1-bar</div>
<div><icon name='g-signal-wifi-1-bar-lock' scale='2'></icon><br>g-signal-wifi-1-bar-lock</div>
<div><icon name='g-signal-wifi-2-bar' scale='2'></icon><br>g-signal-wifi-2-bar</div>
<div><icon name='g-signal-wifi-2-bar-lock' scale='2'></icon><br>g-signal-wifi-2-bar-lock</div>
<div><icon name='g-signal-wifi-3-bar' scale='2'></icon><br>g-signal-wifi-3-bar</div>
<div><icon name='g-signal-wifi-3-bar-lock' scale='2'></icon><br>g-signal-wifi-3-bar-lock</div>
<div><icon name='g-signal-wifi-4-bar' scale='2'></icon><br>g-signal-wifi-4-bar</div>
<div><icon name='g-signal-wifi-4-bar-lock' scale='2'></icon><br>g-signal-wifi-4-bar-lock</div>
<div><icon name='g-signal-wifi-off' scale='2'></icon><br>g-signal-wifi-off</div>
<div><icon name='g-signal-wifi-statusbar-1-bar-26' scale='2'></icon><br>g-signal-wifi-statusbar-1-bar-26</div>
<div><icon name='g-signal-wifi-statusbar-2-bar-26' scale='2'></icon><br>g-signal-wifi-statusbar-2-bar-26</div>
<div><icon name='g-signal-wifi-statusbar-3-bar-26' scale='2'></icon><br>g-signal-wifi-statusbar-3-bar-26</div>
<div><icon name='g-signal-wifi-statusbar-4-bar-26' scale='2'></icon><br>g-signal-wifi-statusbar-4-bar-26</div>
<div><icon name='g-signal-wifi-statusbar-connected-no-internet-1-26' scale='2'></icon><br>g-signal-wifi-statusbar-connected-no-internet-1-26</div>
<div><icon name='g-signal-wifi-statusbar-connected-no-internet-26' scale='2'></icon><br>g-signal-wifi-statusbar-connected-no-internet-26</div>
<div><icon name='g-signal-wifi-statusbar-connected-no-internet-2-26' scale='2'></icon><br>g-signal-wifi-statusbar-connected-no-internet-2-26</div>
<div><icon name='g-signal-wifi-statusbar-connected-no-internet-3-26' scale='2'></icon><br>g-signal-wifi-statusbar-connected-no-internet-3-26</div>
<div><icon name='g-signal-wifi-statusbar-connected-no-internet-4-26' scale='2'></icon><br>g-signal-wifi-statusbar-connected-no-internet-4-26</div>
<div><icon name='g-signal-wifi-statusbar-not-connected-26' scale='2'></icon><br>g-signal-wifi-statusbar-not-connected-26</div>
<div><icon name='g-signal-wifi-statusbar-null-26' scale='2'></icon><br>g-signal-wifi-statusbar-null-26</div>
<div><icon name='g-sim-card' scale='2'></icon><br>g-sim-card</div>
<div><icon name='g-sim-card-alert' scale='2'></icon><br>g-sim-card-alert</div>
<div><icon name='g-skip-next' scale='2'></icon><br>g-skip-next</div>
<div><icon name='g-skip-previous' scale='2'></icon><br>g-skip-previous</div>
<div><icon name='g-slideshow' scale='2'></icon><br>g-slideshow</div>
<div><icon name='g-slow-motion-video' scale='2'></icon><br>g-slow-motion-video</div>
<div><icon name='g-smartphone' scale='2'></icon><br>g-smartphone</div>
<div><icon name='g-smoke-free' scale='2'></icon><br>g-smoke-free</div>
<div><icon name='g-smoking-rooms' scale='2'></icon><br>g-smoking-rooms</div>
<div><icon name='g-sms' scale='2'></icon><br>g-sms</div>
<div><icon name='g-sms-failed' scale='2'></icon><br>g-sms-failed</div>
<div><icon name='g-snooze' scale='2'></icon><br>g-snooze</div>
<div><icon name='g-sort' scale='2'></icon><br>g-sort</div>
<div><icon name='g-sort-by-alpha' scale='2'></icon><br>g-sort-by-alpha</div>
<div><icon name='g-spa' scale='2'></icon><br>g-spa</div>
<div><icon name='g-space-bar' scale='2'></icon><br>g-space-bar</div>
<div><icon name='g-speaker' scale='2'></icon><br>g-speaker</div>
<div><icon name='g-speaker-group' scale='2'></icon><br>g-speaker-group</div>
<div><icon name='g-speaker-notes' scale='2'></icon><br>g-speaker-notes</div>
<div><icon name='g-speaker-notes-off' scale='2'></icon><br>g-speaker-notes-off</div>
<div><icon name='g-speaker-phone' scale='2'></icon><br>g-speaker-phone</div>
<div><icon name='g-spellcheck' scale='2'></icon><br>g-spellcheck</div>
<div><icon name='g-star' scale='2'></icon><br>g-star</div>
<div><icon name='g-star-border' scale='2'></icon><br>g-star-border</div>
<div><icon name='g-star-half' scale='2'></icon><br>g-star-half</div>
<div><icon name='g-star-outline' scale='2'></icon><br>g-star-outline</div>
<div><icon name='g-star-rate' scale='2'></icon><br>g-star-rate</div>
<div><icon name='g-stars' scale='2'></icon><br>g-stars</div>
<div><icon name='g-stay-current-landscape' scale='2'></icon><br>g-stay-current-landscape</div>
<div><icon name='g-stay-current-portrait' scale='2'></icon><br>g-stay-current-portrait</div>
<div><icon name='g-stay-primary-landscape' scale='2'></icon><br>g-stay-primary-landscape</div>
<div><icon name='g-stay-primary-portrait' scale='2'></icon><br>g-stay-primary-portrait</div>
<div><icon name='g-stop' scale='2'></icon><br>g-stop</div>
<div><icon name='g-stop-screen-share' scale='2'></icon><br>g-stop-screen-share</div>
<div><icon name='g-storage' scale='2'></icon><br>g-storage</div>
<div><icon name='g-store' scale='2'></icon><br>g-store</div>
<div><icon name='g-store-mall-directory' scale='2'></icon><br>g-store-mall-directory</div>
<div><icon name='g-straighten' scale='2'></icon><br>g-straighten</div>
<div><icon name='g-streetview' scale='2'></icon><br>g-streetview</div>
<div><icon name='g-strikethrough-s' scale='2'></icon><br>g-strikethrough-s</div>
<div><icon name='g-style' scale='2'></icon><br>g-style</div>
<div><icon name='g-subdirectory-arrow-left' scale='2'></icon><br>g-subdirectory-arrow-left</div>
<div><icon name='g-subdirectory-arrow-right' scale='2'></icon><br>g-subdirectory-arrow-right</div>
<div><icon name='g-subject' scale='2'></icon><br>g-subject</div>
<div><icon name='g-subscriptions' scale='2'></icon><br>g-subscriptions</div>
<div><icon name='g-subtitles' scale='2'></icon><br>g-subtitles</div>
<div><icon name='g-subway' scale='2'></icon><br>g-subway</div>
<div><icon name='g-supervisor-account' scale='2'></icon><br>g-supervisor-account</div>
<div><icon name='g-surround-sound' scale='2'></icon><br>g-surround-sound</div>
<div><icon name='g-swap-calls' scale='2'></icon><br>g-swap-calls</div>
<div><icon name='g-swap-horiz' scale='2'></icon><br>g-swap-horiz</div>
<div><icon name='g-swap-vert' scale='2'></icon><br>g-swap-vert</div>
<div><icon name='g-swap-vert-circle' scale='2'></icon><br>g-swap-vert-circle</div>
<div><icon name='g-swap-vertical-circle' scale='2'></icon><br>g-swap-vertical-circle</div>
<div><icon name='g-switch-camera' scale='2'></icon><br>g-switch-camera</div>
<div><icon name='g-switch-video' scale='2'></icon><br>g-switch-video</div>
<div><icon name='g-sync' scale='2'></icon><br>g-sync</div>
<div><icon name='g-sync-disabled' scale='2'></icon><br>g-sync-disabled</div>
<div><icon name='g-sync-problem' scale='2'></icon><br>g-sync-problem</div>
<div><icon name='g-system-update' scale='2'></icon><br>g-system-update</div>
<div><icon name='g-system-update-alt' scale='2'></icon><br>g-system-update-alt</div>
<div><icon name='g-system-update-tv' scale='2'></icon><br>g-system-update-tv</div>
<div><icon name='g-tab' scale='2'></icon><br>g-tab</div>
<div><icon name='g-tab-unselected' scale='2'></icon><br>g-tab-unselected</div>
<div><icon name='g-tablet' scale='2'></icon><br>g-tablet</div>
<div><icon name='g-tablet-android' scale='2'></icon><br>g-tablet-android</div>
<div><icon name='g-tablet-mac' scale='2'></icon><br>g-tablet-mac</div>
<div><icon name='g-tag-faces' scale='2'></icon><br>g-tag-faces</div>
<div><icon name='g-tap-and-play' scale='2'></icon><br>g-tap-and-play</div>
<div><icon name='g-terrain' scale='2'></icon><br>g-terrain</div>
<div><icon name='g-text-fields' scale='2'></icon><br>g-text-fields</div>
<div><icon name='g-text-format' scale='2'></icon><br>g-text-format</div>
<div><icon name='g-textsms' scale='2'></icon><br>g-textsms</div>
<div><icon name='g-texture' scale='2'></icon><br>g-texture</div>
<div><icon name='g-theaters' scale='2'></icon><br>g-theaters</div>
<div><icon name='g-thumb-down' scale='2'></icon><br>g-thumb-down</div>
<div><icon name='g-thumb-up' scale='2'></icon><br>g-thumb-up</div>
<div><icon name='g-thumbs-up-down' scale='2'></icon><br>g-thumbs-up-down</div>
<div><icon name='g-time-to-leave' scale='2'></icon><br>g-time-to-leave</div>
<div><icon name='g-timelapse' scale='2'></icon><br>g-timelapse</div>
<div><icon name='g-timeline' scale='2'></icon><br>g-timeline</div>
<div><icon name='g-timer-10' scale='2'></icon><br>g-timer-10</div>
<div><icon name='g-timer' scale='2'></icon><br>g-timer</div>
<div><icon name='g-timer-3' scale='2'></icon><br>g-timer-3</div>
<div><icon name='g-timer-auto' scale='2'></icon><br>g-timer-auto</div>
<div><icon name='g-timer-off' scale='2'></icon><br>g-timer-off</div>
<div><icon name='g-title' scale='2'></icon><br>g-title</div>
<div><icon name='g-toc' scale='2'></icon><br>g-toc</div>
<div><icon name='g-today' scale='2'></icon><br>g-today</div>
<div><icon name='g-toll' scale='2'></icon><br>g-toll</div>
<div><icon name='g-tonality' scale='2'></icon><br>g-tonality</div>
<div><icon name='g-touch-app' scale='2'></icon><br>g-touch-app</div>
<div><icon name='g-toys' scale='2'></icon><br>g-toys</div>
<div><icon name='g-track-changes' scale='2'></icon><br>g-track-changes</div>
<div><icon name='g-traffic' scale='2'></icon><br>g-traffic</div>
<div><icon name='g-train' scale='2'></icon><br>g-train</div>
<div><icon name='g-tram' scale='2'></icon><br>g-tram</div>
<div><icon name='g-transfer-within-a-station' scale='2'></icon><br>g-transfer-within-a-station</div>
<div><icon name='g-transform' scale='2'></icon><br>g-transform</div>
<div><icon name='g-translate' scale='2'></icon><br>g-translate</div>
<div><icon name='g-trending-down' scale='2'></icon><br>g-trending-down</div>
<div><icon name='g-trending-flat' scale='2'></icon><br>g-trending-flat</div>
<div><icon name='g-trending-neutral' scale='2'></icon><br>g-trending-neutral</div>
<div><icon name='g-trending-up' scale='2'></icon><br>g-trending-up</div>
<div><icon name='g-tune' scale='2'></icon><br>g-tune</div>
<div><icon name='g-turned-in' scale='2'></icon><br>g-turned-in</div>
<div><icon name='g-turned-in-not' scale='2'></icon><br>g-turned-in-not</div>
<div><icon name='g-tv' scale='2'></icon><br>g-tv</div>
<div><icon name='g-unarchive' scale='2'></icon><br>g-unarchive</div>
<div><icon name='g-undo' scale='2'></icon><br>g-undo</div>
<div><icon name='g-unfold-less' scale='2'></icon><br>g-unfold-less</div>
<div><icon name='g-unfold-more' scale='2'></icon><br>g-unfold-more</div>
<div><icon name='g-update' scale='2'></icon><br>g-update</div>
<div><icon name='g-usb' scale='2'></icon><br>g-usb</div>
<div><icon name='g-verified-user' scale='2'></icon><br>g-verified-user</div>
<div><icon name='g-vertical-align-bottom' scale='2'></icon><br>g-vertical-align-bottom</div>
<div><icon name='g-vertical-align-center' scale='2'></icon><br>g-vertical-align-center</div>
<div><icon name='g-vertical-align-top' scale='2'></icon><br>g-vertical-align-top</div>
<div><icon name='g-vibration' scale='2'></icon><br>g-vibration</div>
<div><icon name='g-video-call' scale='2'></icon><br>g-video-call</div>
<div><icon name='g-video-collection' scale='2'></icon><br>g-video-collection</div>
<div><icon name='g-video-label' scale='2'></icon><br>g-video-label</div>
<div><icon name='g-video-library' scale='2'></icon><br>g-video-library</div>
<div><icon name='g-videocam' scale='2'></icon><br>g-videocam</div>
<div><icon name='g-videocam-off' scale='2'></icon><br>g-videocam-off</div>
<div><icon name='g-videogame-asset' scale='2'></icon><br>g-videogame-asset</div>
<div><icon name='g-view-agenda' scale='2'></icon><br>g-view-agenda</div>
<div><icon name='g-view-array' scale='2'></icon><br>g-view-array</div>
<div><icon name='g-view-carousel' scale='2'></icon><br>g-view-carousel</div>
<div><icon name='g-view-column' scale='2'></icon><br>g-view-column</div>
<div><icon name='g-view-comfy' scale='2'></icon><br>g-view-comfy</div>
<div><icon name='g-view-compact' scale='2'></icon><br>g-view-compact</div>
<div><icon name='g-view-day' scale='2'></icon><br>g-view-day</div>
<div><icon name='g-view-headline' scale='2'></icon><br>g-view-headline</div>
<div><icon name='g-view-list' scale='2'></icon><br>g-view-list</div>
<div><icon name='g-view-module' scale='2'></icon><br>g-view-module</div>
<div><icon name='g-view-quilt' scale='2'></icon><br>g-view-quilt</div>
<div><icon name='g-view-stream' scale='2'></icon><br>g-view-stream</div>
<div><icon name='g-view-week' scale='2'></icon><br>g-view-week</div>
<div><icon name='g-vignette' scale='2'></icon><br>g-vignette</div>
<div><icon name='g-visibility' scale='2'></icon><br>g-visibility</div>
<div><icon name='g-visibility-off' scale='2'></icon><br>g-visibility-off</div>
<div><icon name='g-voice-chat' scale='2'></icon><br>g-voice-chat</div>
<div><icon name='g-voicemail' scale='2'></icon><br>g-voicemail</div>
<div><icon name='g-volume-down' scale='2'></icon><br>g-volume-down</div>
<div><icon name='g-volume-mute' scale='2'></icon><br>g-volume-mute</div>
<div><icon name='g-volume-off' scale='2'></icon><br>g-volume-off</div>
<div><icon name='g-volume-up' scale='2'></icon><br>g-volume-up</div>
<div><icon name='g-vpn-key' scale='2'></icon><br>g-vpn-key</div>
<div><icon name='g-vpn-lock' scale='2'></icon><br>g-vpn-lock</div>
<div><icon name='g-wallet-giftcard' scale='2'></icon><br>g-wallet-giftcard</div>
<div><icon name='g-wallet-membership' scale='2'></icon><br>g-wallet-membership</div>
<div><icon name='g-wallet-travel' scale='2'></icon><br>g-wallet-travel</div>
<div><icon name='g-wallpaper' scale='2'></icon><br>g-wallpaper</div>
<div><icon name='g-warning' scale='2'></icon><br>g-warning</div>
<div><icon name='g-watch' scale='2'></icon><br>g-watch</div>
<div><icon name='g-watch-later' scale='2'></icon><br>g-watch-later</div>
<div><icon name='g-wb-auto' scale='2'></icon><br>g-wb-auto</div>
<div><icon name='g-wb-cloudy' scale='2'></icon><br>g-wb-cloudy</div>
<div><icon name='g-wb-incandescent' scale='2'></icon><br>g-wb-incandescent</div>
<div><icon name='g-wb-iridescent' scale='2'></icon><br>g-wb-iridescent</div>
<div><icon name='g-wb-irradescent' scale='2'></icon><br>g-wb-irradescent</div>
<div><icon name='g-wb-sunny' scale='2'></icon><br>g-wb-sunny</div>
<div><icon name='g-wc' scale='2'></icon><br>g-wc</div>
<div><icon name='g-web' scale='2'></icon><br>g-web</div>
<div><icon name='g-weekend' scale='2'></icon><br>g-weekend</div>
<div><icon name='g-whatshot' scale='2'></icon><br>g-whatshot</div>
<div><icon name='g-widgets' scale='2'></icon><br>g-widgets</div>
<div><icon name='g-wifi' scale='2'></icon><br>g-wifi</div>
<div><icon name='g-wifi-lock' scale='2'></icon><br>g-wifi-lock</div>
<div><icon name='g-wifi-tethering' scale='2'></icon><br>g-wifi-tethering</div>
<div><icon name='g-work' scale='2'></icon><br>g-work</div>
<div><icon name='g-wrap-text' scale='2'></icon><br>g-wrap-text</div>
<div><icon name='g-youtube-searched-for' scale='2'></icon><br>g-youtube-searched-for</div>
<div><icon name='g-zoom-in' scale='2'></icon><br>g-zoom-in</div>
<div><icon name='g-zoom-out' scale='2'></icon><br>g-zoom-out</div>
<div><icon name='g-zoom-out-map' scale='2'></icon><br>g-zoom-out-map</div>

</div>
</template>

<script>
  import {Icon} from '@wxt/control'

  export default {
    components: {
      Icon
    }
  }

</script>
<style>
  .icondiv {
    font-family:'RobotoDraft', Arial, sans-serif;
    font-size: 10px;
  }
  .icondiv svg {
    width: 48px;
    height: 48px;
  }
  .icondiv div {
    width: 54px;
    display:inline-block;
    text-align:center;
    white-space:wrap;
    vertical-align:top;
    padding:4px;
  }
  .icondiv h1, h2 {
    padding:12px;
  }
</style>